# 进程号
pid = "./run/web.pid"
# 统一时区设置。项目中的时间获取请使用xtime.Now()
timezone = "Local"

[http]
    # 端口地址
    addr = ":18089"
    # 日志文件
    log = "./log/http.log"

[config]
    [config.etcd]
        # 客户端连接地址
        addrs = ["127.0.0.1:2379"]
        # 客户端拨号超时时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为5s
        dialTimeout = "5s"
        # 路径。默认为/config
        path = "/config"
        # 读写模式。可选：read-only | read-write，默认为read-only
        mode = "read-only"

[registry]
    [registry.consul]
        # 客户端连接地址
        addr = "127.0.0.1:8500"
        # 是否启用健康检查
        healthCheck = true
        # 健康检查时间间隔（秒），仅在启用健康检查后生效
        healthCheckInterval = 10
        # 健康检查超时时间（秒），仅在启用健康检查后生效
        healthCheckTimeout = 5
        # 是否启用心跳检查
        heartbeatCheck = true
        # 心跳检查时间间隔（秒），仅在启用心跳检查后生效
        heartbeatCheckInterval = 10
        # 健康检测失败后自动注销服务时间（秒）
        deregisterCriticalServiceAfter = 30

[transport]
    [transport.rpcx]
        # RPCX服务器相关配置
        [transport.rpcx.client]
            # 证书文件
            certFile = ""
            # 证书域名
            serverName = ""
            # 连接池大小，默认为10
            poolSize = 32

[log]
    [log.zap]
        # 日志输出文件
        file = "./log/xbase.log"
        # 日志输出级别，可选：debug | info | warn | error | fatal | panic
        level = "debug"
        # 日志输出格式，可选：text | json
        format = "text"
        # 是否输出到终端
        stdout = false
        # 时间格式，标准库时间格式
        timeFormat = "2006/01/02 15:04:05.000000"
        # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
        stackLevel = "error"
        # 文件最大留存时间，d:天、h:时、m:分、s:秒
        fileMaxAge = "7d"
        # 文件最大尺寸限制，单位（MB）
        fileMaxSize = 100
        # 文件切割方式
        fileCutRule = "day"
        # 是否启用调用文件全路径
        callerFullPath = false
        # 是否启用分级存储
        classifiedStorage = false

[jwt]
    # jwt发行方
    issuer = "xrobot"
    # 过期时间
    validDuration = 7200
    # 秘钥KEY
    secretKey = "MZlD9KpffCPh7oJtCaDoqFQE1cqZyVKfoxeQdYy4mkYKkBUCQQDQpPO7MmTPmuLI"
    # 身份认证KEY
    identityKey = "uid"
    # TOKEN查找位置
    locations = "header:Authorization"
    # 存储组件
    [jwt.store]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号
        db = 9
        # 用户名
        username = ""
        # 密码
        password = "robotEm24321PwdRed"
        # 最大重试次数
        maxRetries = 3

[doc]
    # API版本
    version = "1.0.0"
    # API标题
    title = "API文档"
    # API描述
    description = "API文档"
    # API地址
    host = "http://192.168.0.108:8081"
    # API基础路径
    basePath = "/"
    # API协议
    schemes = ["http", "https"]

[backblaze]
    # BackBlaze默认配置
    [backblaze.default]
        # 账号
        account = "ad9fc922950a"
        # 密钥
        key = "005ae24f2177b8c8ab870d528fd0128464ff77e6ec"
        # 桶
        bucket = "xrobot-test"
        # 基础路径
        basePath = "upload/"
    [backblaze.avatar]
        # 基础路径
        basePath = "../resource/upload/avatar/"
        # 资源静态路径
        basePathUrl = "resource/upload/avatar/"
[redis]
    # 默认
    [redis.default]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号
        db = 3
        # 用户名
        username = ""
        # 密码
        password = "robotEm24321PwdRed"
        # 最大重试次数
        maxRetries = 3
    # wallet redis
    [redis.userwallet]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号
        db = 4
        # 用户名
        username = ""
        # 密码
        password = "crot568Ze#mTeQC"
        # 最大重试次数
        maxRetries = 3
    #用户输入按钮检测
    [redis.waitForInput]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号 用户输入按钮检测 连接5
        db = 5
        # 用户名
        username = ""
        # 密码
        password = "robotEm24321PwdRed"
        # 最大重试次数
        maxRetries = 3
    #加密货币用的库
    [redis.cryptocurrencies]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号 用户输入按钮检测 连接5
        db = 6
        # 用户名
        username = ""
        # 密码
        password = "robotEm24321PwdRed"
        # 最大重试次数
        maxRetries = 3
        #配置缓存
    [redis.option]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号 用户输入按钮检测 连接5
        db = 7
        # 用户名
        username = ""
        # 密码
        password = "robotEm24321PwdRed"
        # 最大重试次数
        maxRetries = 3